SELECT * FROM USERS

SELECT * FROM MUSIC

SELECT * FROM MUSIC WHERE NAME = 3 ORDER BY ARTIST ASC

SELECT title,ARTIST  FROM MUSIC WHERE TITLE  = '끝났다는 것은 다시 시작된다는 것을'

SELECT * FROM MUSIC WHERE TITLE  = 'vitriol (acoustic version)'

DELETE FROM MUSIC WHERE MUSIC_ID = 252