# port
server:
  port: 9090

# encoding  
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  
spring:
  datasource:
    url: jdbc:oracle:thin:@juhohome.iptime.org:1521:xe
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: juho
    password: 1234
    
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      auto-commit: false
      connection-test-query: select 1 from dual
      pool-name: jhpool
  servlet:
    multipart:
      max-file-size: 10MB
            
  mvc:
    view:
     prefix: /WEB-INF/views/
     suffix: .html
    
    
  thymeleaf:
    prefix: /WEB-INF/views/
    suffix: .html
    static-path-pattern: /resources/**
    
  jpa:
    generate-ddl: true
    show-sql: true
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: none

mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  config-location: classpath:mybatis-config.xml  
